ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'pdf_export_updated';

ALTER TABLE "SessionGroup"
ADD COLUMN "pdfExportError" TEXT,
ADD COLUMN "pdfPageWidth" DOUBLE PRECISION NOT NULL DEFAULT 210,
ADD COLUMN "pdfPageHeight" DOUBLE PRECISION NOT NULL DEFAULT 297,
ADD COLUMN "pdfPageUnit" TEXT NOT NULL DEFAULT 'mm',
ADD COLUMN "pdfFormatVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "pdfExportFormatVersion" INTEGER;
