import { gql } from '@apollo/client';

const GQL_MY_INSTANCES = gql`
  query MyInstances {
    myInstances {
      id
      serverId
      name
      hasPassword
    }
  }
`;

const GQL_SET_INSTANCE_PASSWORD = gql`
  mutation SetInstancePassword($instanceId: ID!, $password: String) {
    setInstancePassword(instanceId: $instanceId, password: $password)
  }
`;

// Hooks are auto-generated by `make gql` — import from __generated__/useInstanceSettings.generated.ts
