/** Map file extensions to Monaco editor language identifiers. */
export function getLanguageFromPath(filePath: string): string {
  const ext = filePath.split(".").pop()?.toLowerCase();
  const map: Record<string, string> = {
    ts: "typescript",
    tsx: "typescript",
    js: "javascript",
    jsx: "javascript",
    json: "json",
    jsonc: "json",
    md: "markdown",
    mdx: "markdown",
    html: "html",
    htm: "html",
    css: "css",
    scss: "scss",
    less: "less",
    py: "python",
    rb: "ruby",
    go: "go",
    rs: "rust",
    java: "java",
    c: "c",
    cpp: "cpp",
    h: "c",
    hpp: "cpp",
    cs: "csharp",
    swift: "swift",
    kt: "kotlin",
    yaml: "yaml",
    yml: "yaml",
    toml: "ini",
    xml: "xml",
    svg: "xml",
    sql: "sql",
    sh: "shell",
    bash: "shell",
    zsh: "shell",
    dockerfile: "dockerfile",
    graphql: "graphql",
    gql: "graphql",
    prisma: "graphql",
    vue: "html",
    svelte: "html",
    env: "ini",
    ini: "ini",
    conf: "ini",
    txt: "plaintext",
    lock: "json",
  };
  return map[ext ?? ""] ?? "plaintext";
}
