import type { Event } from "@trace/gql";
import { useEntityStore, eventScopeKey } from "../stores/entity";
import { useAuthStore } from "../stores/auth";

const OPTIMISTIC_PREFIX = "optimistic:";

// ---------------------------------------------------------------------------
// Pending-queue helpers
// ---------------------------------------------------------------------------

/** Push an item into a Map<key, T[]> queue, creating the array if needed. */
function enqueue<T>(map: Map<string, T[]>, key: string, item: T): void {
  let queue = map.get(key);
  if (!queue) {
    queue = [];
    map.set(key, queue);
  }
  queue.push(item);
}

/** Remove a specific item from a Map<key, T[]> queue by index search. */
function dequeue<T>(map: Map<string, T[]>, key: string, predicate: (item: T) => boolean): void {
  const queue = map.get(key);
  if (!queue) return;
  const idx = queue.findIndex(predicate);
  if (idx !== -1) queue.splice(idx, 1);
  if (queue.length === 0) map.delete(key);
}

/** Shift (drain) the oldest item from a Map<key, T[]> queue. */
function drainOldest<T>(map: Map<string, T[]>, key: string): T | undefined {
  const queue = map.get(key);
  if (!queue || queue.length === 0) return undefined;
  const entry = queue.shift()!;
  if (queue.length === 0) map.delete(key);
  return entry;
}

// ---------------------------------------------------------------------------
// Pending optimistic tracking
// ---------------------------------------------------------------------------

type PendingChatEntry = { tempMessageId: string; tempEventId: string };

/**
 * Tracks pending optimistic chat messages so the subscription handler can
 * atomically remove them when the real message arrives (preventing the brief
 * duplicate / flash).
 */
const pendingChatOptimistic = new Map<string, PendingChatEntry[]>();

/**
 * Drain (return and remove) the oldest pending optimistic entry for the given
 * chatId, if any. Used by the subscription handler to clean up the optimistic
 * message atomically when the real one arrives.
 */
export function drainPendingOptimisticChat(chatId: string): PendingChatEntry | undefined {
  return drainOldest(pendingChatOptimistic, chatId);
}

/** Returns true if the event ID was generated by an optimistic insert */
export function isOptimisticEvent(id: string): boolean {
  return id.startsWith(OPTIMISTIC_PREFIX);
}

/**
 * Tracks pending optimistic session message events so the subscription handler
 * can atomically remove them when the real event arrives.
 */
const pendingSessionOptimistic = new Map<string, string[]>();

/**
 * Drain (return and remove) the oldest pending optimistic session event entry
 * for the given sessionId, if any.
 */
export function drainPendingOptimisticSession(sessionId: string): string | undefined {
  return drainOldest(pendingSessionOptimistic, sessionId);
}

/**
 * Insert an optimistic `message_sent` event into the session's scoped
 * event bucket so it appears instantly in the session log.
 *
 * Returns the temp event ID for later cleanup.
 */
export function optimisticallyInsertSessionMessage(sessionId: string, text: string): string {
  const user = useAuthStore.getState().user;
  const now = new Date().toISOString();
  const tempId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const scopeKey = eventScopeKey("session", sessionId);

  const event: Event = {
    id: tempId,
    scopeType: "session",
    scopeId: sessionId,
    eventType: "message_sent",
    payload: { text } as unknown as Record<string, unknown>,
    actor: {
      type: "user",
      id: user?.id ?? "",
      name: user?.name ?? null,
      avatarUrl: user?.avatarUrl ?? null,
    },
    parentId: null,
    timestamp: now,
    metadata: null,
  };

  useEntityStore.getState().upsertScopedEvent(scopeKey, tempId, event);

  // Track pending so the subscription handler can clean up atomically
  enqueue(pendingSessionOptimistic, sessionId, tempId);

  return tempId;
}

/**
 * Remove an optimistic event from the session's scoped event bucket.
 */
export function removeOptimisticSessionMessage(sessionId: string, tempEventId: string): void {
  dequeue(pendingSessionOptimistic, sessionId, (id) => id === tempEventId);

  const scopeKey = eventScopeKey("session", sessionId);
  useEntityStore.setState((state) => {
    const bucket = state.eventsByScope[scopeKey];
    if (!bucket || !bucket[tempEventId]) return state;
    const { [tempEventId]: _, ...rest } = bucket;
    return { eventsByScope: { ...state.eventsByScope, [scopeKey]: rest } };
  });
}

export function reconcileOptimisticSessionMessage(
  sessionId: string,
  tempEventId: string,
  realEventId: string,
): void {
  dequeue(pendingSessionOptimistic, sessionId, (id) => id === tempEventId);

  const scopeKey = eventScopeKey("session", sessionId);
  useEntityStore.setState((state) => {
    const bucket = state.eventsByScope[scopeKey];
    const optimisticEvent = bucket?.[tempEventId];
    if (!bucket || !optimisticEvent) return state;

    const { [tempEventId]: _, ...rest } = bucket;
    if (rest[realEventId]) {
      return { eventsByScope: { ...state.eventsByScope, [scopeKey]: rest } };
    }

    return {
      eventsByScope: {
        ...state.eventsByScope,
        [scopeKey]: {
          ...rest,
          [realEventId]: { ...optimisticEvent, id: realEventId },
        },
      },
    };
  });
}

/** Result of inserting an optimistic chat message — both IDs needed for cleanup */
export interface OptimisticChatIds {
  messageId: string;
  eventId: string;
}

/**
 * Insert an optimistic chat message into the messages table and
 * a corresponding event into the chat's scoped event bucket.
 *
 * Returns both temp IDs so the caller can pass them directly to removal
 * (avoids an O(n) scan of the event bucket).
 */
export function optimisticallyInsertChatMessage(
  chatId: string,
  html: string,
  parentId?: string | null,
): OptimisticChatIds {
  const user = useAuthStore.getState().user;
  const now = new Date().toISOString();
  const tempEventId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const tempMessageId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const scopeKey = eventScopeKey("chat", chatId);

  const actor = {
    type: "user" as const,
    id: user?.id ?? "",
    name: user?.name ?? null,
    avatarUrl: user?.avatarUrl ?? null,
  };

  // Insert message entity
  useEntityStore.getState().upsert("messages", tempMessageId, {
    id: tempMessageId,
    chatId,
    channelId: null,
    text: html,
    html,
    mentions: null,
    parentMessageId: parentId ?? null,
    replyCount: 0,
    latestReplyAt: null,
    threadRepliers: [],
    actor,
    createdAt: now,
    updatedAt: now,
    editedAt: null,
    deletedAt: null,
  });

  // Insert scoped event
  const event: Event = {
    id: tempEventId,
    scopeType: "chat",
    scopeId: chatId,
    eventType: "message_sent",
    payload: { messageId: tempMessageId, text: html, html } as unknown as Record<string, unknown>,
    actor,
    parentId: null,
    timestamp: now,
    metadata: null,
  };

  useEntityStore.getState().upsertScopedEvent(scopeKey, tempEventId, event);

  // Track pending so the subscription handler can clean up atomically
  enqueue(pendingChatOptimistic, chatId, { tempMessageId, tempEventId });

  return { messageId: tempMessageId, eventId: tempEventId };
}

/**
 * Remove an optimistic chat message when the real one arrives.
 */
export function removeOptimisticChatMessage(
  chatId: string,
  tempMessageId: string,
  tempEventId: string,
): void {
  dequeue(pendingChatOptimistic, chatId, (e) => e.tempMessageId === tempMessageId);

  const scopeKey = eventScopeKey("chat", chatId);

  // Remove message entity + scoped event atomically
  useEntityStore.setState((state) => {
    const messages = { ...state.messages };
    delete messages[tempMessageId];

    const bucket = state.eventsByScope[scopeKey];
    if (!bucket || !bucket[tempEventId]) {
      return { messages };
    }
    const { [tempEventId]: _, ...rest } = bucket;
    return {
      messages,
      eventsByScope: { ...state.eventsByScope, [scopeKey]: rest },
    };
  });
}

export function reconcileOptimisticChatMessage(
  chatId: string,
  tempMessageId: string,
  tempEventId: string,
  realMessageId: string,
): void {
  dequeue(pendingChatOptimistic, chatId, (e) => e.tempMessageId === tempMessageId);

  const scopeKey = eventScopeKey("chat", chatId);
  useEntityStore.setState((state) => {
    const messages = { ...state.messages };
    const optimisticMessage = messages[tempMessageId];
    delete messages[tempMessageId];
    if (optimisticMessage && !messages[realMessageId]) {
      messages[realMessageId] = { ...optimisticMessage, id: realMessageId };
    }

    const bucket = state.eventsByScope[scopeKey];
    if (!bucket || !bucket[tempEventId]) {
      return { messages };
    }
    const { [tempEventId]: _, ...rest } = bucket;
    return {
      messages,
      eventsByScope: { ...state.eventsByScope, [scopeKey]: rest },
    };
  });
}
