import type { Event } from "@trace/gql";
import { useEntityStore, eventScopeKey } from "../stores/entity";
import { useAuthStore } from "../stores/auth";

const OPTIMISTIC_PREFIX = "optimistic:";

/** Delay (ms) before removing optimistic events, to let the subscription deliver the real event first */
const REMOVAL_DELAY_MS = 200;

/** Returns true if the event ID was generated by an optimistic insert */
export function isOptimisticEvent(id: string): boolean {
  return id.startsWith(OPTIMISTIC_PREFIX);
}

/**
 * Insert an optimistic `message_sent` event into the session's scoped
 * event bucket so it appears instantly in the session log.
 *
 * Returns the temp event ID for later cleanup.
 */
export function optimisticallyInsertSessionMessage(
  sessionId: string,
  text: string,
): string {
  const user = useAuthStore.getState().user;
  const now = new Date().toISOString();
  const tempId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const scopeKey = eventScopeKey("session", sessionId);

  const event: Event = {
    id: tempId,
    scopeType: "session",
    scopeId: sessionId,
    eventType: "message_sent",
    payload: { text } as unknown as Record<string, unknown>,
    actor: {
      type: "user",
      id: user?.id ?? "",
      name: user?.name ?? null,
      avatarUrl: user?.avatarUrl ?? null,
    },
    parentId: null,
    timestamp: now,
    metadata: null,
  };

  useEntityStore.getState().upsertScopedEvent(scopeKey, tempId, event);
  return tempId;
}

/**
 * Remove an optimistic event from the session's scoped event bucket.
 * Delayed slightly to let the real event arrive via subscription first,
 * avoiding a flicker where neither optimistic nor real event is visible.
 */
export function removeOptimisticSessionMessage(
  sessionId: string,
  tempEventId: string,
): void {
  setTimeout(() => {
    const scopeKey = eventScopeKey("session", sessionId);
    useEntityStore.setState((state) => {
      const bucket = state.eventsByScope[scopeKey];
      if (!bucket || !bucket[tempEventId]) return state;
      const { [tempEventId]: _, ...rest } = bucket;
      return { eventsByScope: { ...state.eventsByScope, [scopeKey]: rest } };
    });
  }, REMOVAL_DELAY_MS);
}

/** Result of inserting an optimistic chat message — both IDs needed for cleanup */
export interface OptimisticChatIds {
  messageId: string;
  eventId: string;
}

/**
 * Insert an optimistic chat message into the messages table and
 * a corresponding event into the chat's scoped event bucket.
 *
 * Returns both temp IDs so the caller can pass them directly to removal
 * (avoids an O(n) scan of the event bucket).
 */
export function optimisticallyInsertChatMessage(
  chatId: string,
  html: string,
  parentId?: string | null,
): OptimisticChatIds {
  const user = useAuthStore.getState().user;
  const now = new Date().toISOString();
  const tempEventId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const tempMessageId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const scopeKey = eventScopeKey("chat", chatId);

  const actor = {
    type: "user" as const,
    id: user?.id ?? "",
    name: user?.name ?? null,
    avatarUrl: user?.avatarUrl ?? null,
  };

  // Insert message entity
  useEntityStore.getState().upsert("messages", tempMessageId, {
    id: tempMessageId,
    chatId,
    channelId: null,
    text: html,
    html,
    mentions: null,
    parentMessageId: parentId ?? null,
    replyCount: 0,
    latestReplyAt: null,
    threadRepliers: [],
    actor,
    createdAt: now,
    updatedAt: now,
    editedAt: null,
    deletedAt: null,
  });

  // Insert scoped event
  const event: Event = {
    id: tempEventId,
    scopeType: "chat",
    scopeId: chatId,
    eventType: "message_sent",
    payload: { messageId: tempMessageId, text: html, html } as unknown as Record<string, unknown>,
    actor,
    parentId: null,
    timestamp: now,
    metadata: null,
  };

  useEntityStore.getState().upsertScopedEvent(scopeKey, tempEventId, event);
  return { messageId: tempMessageId, eventId: tempEventId };
}

/**
 * Remove an optimistic chat message when the real one arrives.
 * Delayed slightly to let the subscription deliver the real message first.
 */
export function removeOptimisticChatMessage(
  chatId: string,
  tempMessageId: string,
  tempEventId: string,
): void {
  setTimeout(() => {
    const scopeKey = eventScopeKey("chat", chatId);

    // Remove message entity + scoped event atomically
    useEntityStore.setState((state) => {
      const messages = { ...state.messages };
      delete messages[tempMessageId];

      const bucket = state.eventsByScope[scopeKey];
      if (!bucket || !bucket[tempEventId]) {
        return { messages };
      }
      const { [tempEventId]: _, ...rest } = bucket;
      return {
        messages,
        eventsByScope: { ...state.eventsByScope, [scopeKey]: rest },
      };
    });
  }, REMOVAL_DELAY_MS);
}
