import type { Event, Message } from "@trace/gql";
import { asJsonObject } from "@trace/shared";
import { useEntityStore, eventScopeKey } from "../stores/entity";
import { useAuthStore } from "../stores/auth";

const OPTIMISTIC_PREFIX = "optimistic:";

/** Returns true if the event ID was generated by an optimistic insert */
export function isOptimisticEvent(id: string): boolean {
  return id.startsWith(OPTIMISTIC_PREFIX);
}

/** Max age (ms) before a pending entry is considered stale and swept. */
const PENDING_TTL_MS = 30_000;

export interface PendingSessionEntry {
  tempEventId: string;
  clientMutationId: string;
  expectedRealEventId?: string;
  createdAt: number;
}

export interface PendingChatEntry {
  tempMessageId: string;
  tempEventId: string;
  clientMutationId: string;
  expectedRealMessageId?: string;
  createdAt: number;
}

const pendingSessionOptimistic = new Map<string, PendingSessionEntry[]>();
const pendingChatOptimistic = new Map<string, PendingChatEntry[]>();

/** Remove entries older than PENDING_TTL_MS from all pending Maps. */
function sweepStalePending(): void {
  const now = Date.now();
  for (const [key, queue] of pendingSessionOptimistic) {
    const fresh = queue.filter((e) => now - e.createdAt < PENDING_TTL_MS);
    if (fresh.length === 0) pendingSessionOptimistic.delete(key);
    else pendingSessionOptimistic.set(key, fresh);
  }
  for (const [key, queue] of pendingChatOptimistic) {
    const fresh = queue.filter((e) => now - e.createdAt < PENDING_TTL_MS);
    if (fresh.length === 0) pendingChatOptimistic.delete(key);
    else pendingChatOptimistic.set(key, fresh);
  }
}

// Periodic sweep to prevent unbounded growth under degraded network conditions
setInterval(sweepStalePending, PENDING_TTL_MS);

function enqueue<T>(map: Map<string, T[]>, key: string, item: T): void {
  const queue = map.get(key);
  if (queue) {
    queue.push(item);
    return;
  }
  map.set(key, [item]);
}

function dequeue<T>(map: Map<string, T[]>, key: string, predicate: (item: T) => boolean): void {
  const queue = map.get(key);
  if (!queue) return;
  const idx = queue.findIndex(predicate);
  if (idx === -1) return;
  queue.splice(idx, 1);
  if (queue.length === 0) map.delete(key);
}

function takeMatching<T>(
  map: Map<string, T[]>,
  key: string,
  predicate: (item: T) => boolean,
): T | undefined {
  const queue = map.get(key);
  if (!queue) return undefined;
  const idx = queue.findIndex(predicate);
  if (idx === -1) return undefined;
  const [entry] = queue.splice(idx, 1);
  if (queue.length === 0) map.delete(key);
  return entry;
}

function takeAllMatching<T>(
  map: Map<string, T[]>,
  key: string,
  predicate: (item: T) => boolean,
): T[] {
  const queue = map.get(key);
  if (!queue) return [];

  const matched: T[] = [];
  const remaining: T[] = [];
  for (const item of queue) {
    if (predicate(item)) {
      matched.push(item);
    } else {
      remaining.push(item);
    }
  }

  if (matched.length === 0) return [];
  if (remaining.length === 0) {
    map.delete(key);
  } else {
    map.set(key, remaining);
  }
  return matched;
}

function patchPending<T>(
  map: Map<string, T[]>,
  key: string,
  predicate: (item: T) => boolean,
  patch: (item: T) => void,
): void {
  const queue = map.get(key);
  if (!queue) return;
  const entry = queue.find(predicate);
  if (!entry) return;
  patch(entry);
}

function createClientMutationId(): string {
  return `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
}

function getClientMutationId(event: Event): string | null {
  const payload = asJsonObject(event.payload);
  return typeof payload?.clientMutationId === "string" ? payload.clientMutationId : null;
}

function takePendingSessionEntry(sessionId: string, event: Event): PendingSessionEntry | undefined {
  const clientMutationId = getClientMutationId(event);
  return takeMatching(
    pendingSessionOptimistic,
    sessionId,
    (entry) =>
      (clientMutationId !== null && entry.clientMutationId === clientMutationId) ||
      entry.expectedRealEventId === event.id,
  );
}

export function takePendingOptimisticSession(
  sessionId: string,
  event: Event,
): PendingSessionEntry | undefined {
  return takePendingSessionEntry(sessionId, event);
}

export function takePendingOptimisticChat(
  chatId: string,
  event: Event,
): PendingChatEntry | undefined {
  const clientMutationId = getClientMutationId(event);
  const payload = asJsonObject(event.payload);
  const realMessageId = typeof payload?.messageId === "string" ? payload.messageId : null;

  return takeMatching(
    pendingChatOptimistic,
    chatId,
    (entry) =>
      (clientMutationId !== null && entry.clientMutationId === clientMutationId) ||
      entry.expectedRealMessageId === realMessageId,
  );
}

function upsertSessionEvents(scopeKey: string, events: Array<Event & { id: string }>): void {
  useEntityStore.setState((state) => {
    const bucket = { ...(state.eventsByScope[scopeKey] ?? {}) };
    for (const event of events) {
      bucket[event.id] = event;
    }
    return { eventsByScope: { ...state.eventsByScope, [scopeKey]: bucket } };
  });
}

export interface OptimisticSessionIds {
  eventId: string;
  clientMutationId: string;
}

/**
 * Insert an optimistic `message_sent` event into the session's scoped
 * event bucket so it appears instantly in the session log.
 */
export function optimisticallyInsertSessionMessage(
  sessionId: string,
  text: string,
): OptimisticSessionIds {
  const user = useAuthStore.getState().user;
  const now = new Date().toISOString();
  const clientMutationId = createClientMutationId();
  const tempId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const scopeKey = eventScopeKey("session", sessionId);

  const event: Event = {
    id: tempId,
    scopeType: "session",
    scopeId: sessionId,
    eventType: "message_sent",
    payload: { text, clientMutationId } as unknown as Record<string, unknown>,
    actor: {
      type: "user",
      id: user?.id ?? "",
      name: user?.name ?? null,
      avatarUrl: user?.avatarUrl ?? null,
    },
    parentId: null,
    timestamp: now,
    metadata: null,
  };

  useEntityStore.getState().upsertScopedEvent(scopeKey, tempId, event);

  enqueue(pendingSessionOptimistic, sessionId, { tempEventId: tempId, clientMutationId, createdAt: Date.now() });

  return { eventId: tempId, clientMutationId };
}

export function removeOptimisticSessionMessage(sessionId: string, tempEventId: string): void {
  dequeue(pendingSessionOptimistic, sessionId, (entry) => entry.tempEventId === tempEventId);

  const scopeKey = eventScopeKey("session", sessionId);
  useEntityStore.setState((state) => {
    const bucket = state.eventsByScope[scopeKey];
    if (!bucket || !bucket[tempEventId]) return state;
    const { [tempEventId]: _, ...rest } = bucket;
    return { eventsByScope: { ...state.eventsByScope, [scopeKey]: rest } };
  });
}

export function reconcileOptimisticSessionMessage(
  sessionId: string,
  tempEventId: string,
  realEventId: string,
): void {
  patchPending(
    pendingSessionOptimistic,
    sessionId,
    (entry) => entry.tempEventId === tempEventId,
    (entry) => {
      entry.expectedRealEventId = realEventId;
    },
  );
}

export function upsertSessionEventWithOptimisticResolution(
  sessionId: string,
  event: Event & { id: string },
): void {
  const scopeKey = eventScopeKey("session", sessionId);
  const pending = takePendingSessionEntry(sessionId, event);
  if (!pending) {
    useEntityStore.getState().upsertScopedEvent(scopeKey, event.id, event);
    return;
  }

  useEntityStore.setState((state) => {
    const bucket = { ...(state.eventsByScope[scopeKey] ?? {}) };
    delete bucket[pending.tempEventId];
    bucket[event.id] = event;
    return {
      eventsByScope: { ...state.eventsByScope, [scopeKey]: bucket },
    };
  });
}

export function upsertFetchedSessionEventsWithOptimisticResolution(
  sessionId: string,
  events: Array<Event & { id: string }>,
): void {
  const scopeKey = eventScopeKey("session", sessionId);
  const eventIds = new Set(events.map((event) => event.id));
  const matched = takeAllMatching(
    pendingSessionOptimistic,
    sessionId,
    (entry) => !!entry.expectedRealEventId && eventIds.has(entry.expectedRealEventId),
  );

  if (matched.length === 0) {
    upsertSessionEvents(scopeKey, events);
    return;
  }

  useEntityStore.setState((state) => {
    const bucket = { ...(state.eventsByScope[scopeKey] ?? {}) };
    for (const event of events) {
      bucket[event.id] = event;
    }
    for (const entry of matched) {
      delete bucket[entry.tempEventId];
    }
    return { eventsByScope: { ...state.eventsByScope, [scopeKey]: bucket } };
  });
}

export interface OptimisticChatIds {
  messageId: string;
  eventId: string;
  clientMutationId: string;
}

/**
 * Insert an optimistic chat message into the messages table and
 * a corresponding event into the chat's scoped event bucket.
 */
export function optimisticallyInsertChatMessage(
  chatId: string,
  html: string,
  parentId?: string | null,
): OptimisticChatIds {
  const user = useAuthStore.getState().user;
  const now = new Date().toISOString();
  const clientMutationId = createClientMutationId();
  const tempEventId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const tempMessageId = `${OPTIMISTIC_PREFIX}${crypto.randomUUID()}`;
  const scopeKey = eventScopeKey("chat", chatId);

  const actor = {
    type: "user" as const,
    id: user?.id ?? "",
    name: user?.name ?? null,
    avatarUrl: user?.avatarUrl ?? null,
  };

  // Insert message entity
  useEntityStore.getState().upsert("messages", tempMessageId, {
    id: tempMessageId,
    chatId,
    channelId: null,
    text: html,
    html,
    mentions: null,
    parentMessageId: parentId ?? null,
    replyCount: 0,
    latestReplyAt: null,
    threadRepliers: [],
    actor,
    createdAt: now,
    updatedAt: now,
    editedAt: null,
    deletedAt: null,
  });

  // Insert scoped event
  const event: Event = {
    id: tempEventId,
    scopeType: "chat",
    scopeId: chatId,
    eventType: "message_sent",
    payload: {
      messageId: tempMessageId,
      text: html,
      html,
      parentMessageId: parentId ?? null,
      clientMutationId,
    } as unknown as Record<string, unknown>,
    actor,
    parentId: null,
    timestamp: now,
    metadata: null,
  };

  useEntityStore.getState().upsertScopedEvent(scopeKey, tempEventId, event);

  enqueue(pendingChatOptimistic, chatId, {
    tempMessageId,
    tempEventId,
    clientMutationId,
    createdAt: Date.now(),
  });

  return { messageId: tempMessageId, eventId: tempEventId, clientMutationId };
}

export function removeOptimisticChatMessage(
  chatId: string,
  tempMessageId: string,
  tempEventId: string,
): void {
  dequeue(
    pendingChatOptimistic,
    chatId,
    (entry) => entry.tempMessageId === tempMessageId && entry.tempEventId === tempEventId,
  );

  const scopeKey = eventScopeKey("chat", chatId);

  // Remove message entity + scoped event atomically
  useEntityStore.setState((state) => {
    const messages = { ...state.messages };
    delete messages[tempMessageId];

    const bucket = state.eventsByScope[scopeKey];
    if (!bucket || !bucket[tempEventId]) {
      return { messages };
    }
    const { [tempEventId]: _, ...rest } = bucket;
    return {
      messages,
      eventsByScope: { ...state.eventsByScope, [scopeKey]: rest },
    };
  });
}

export function reconcileOptimisticChatMessage(
  chatId: string,
  tempMessageId: string,
  tempEventId: string,
  realMessageId: string,
): void {
  patchPending(
    pendingChatOptimistic,
    chatId,
    (entry) => entry.tempMessageId === tempMessageId && entry.tempEventId === tempEventId,
    (entry) => {
      entry.expectedRealMessageId = realMessageId;
    },
  );
}

export function upsertFetchedChatMessagesWithOptimisticResolution(
  chatId: string,
  messages: Array<Message & { id: string }>,
): void {
  const scopeKey = eventScopeKey("chat", chatId);
  const realMessageIds = new Set(messages.map((message) => message.id));
  const matched = takeAllMatching(
    pendingChatOptimistic,
    chatId,
    (entry) => !!entry.expectedRealMessageId && realMessageIds.has(entry.expectedRealMessageId),
  );

  useEntityStore.setState((state) => {
    const nextMessages = { ...state.messages };
    for (const message of messages) {
      nextMessages[message.id] = message;
    }

    if (matched.length === 0) {
      return { messages: nextMessages };
    }

    let nextEventsByScope = state.eventsByScope;
    let bucket = state.eventsByScope[scopeKey];
    let bucketChanged = false;

    for (const entry of matched) {
      delete nextMessages[entry.tempMessageId];
      if (bucket?.[entry.tempEventId]) {
        if (!bucketChanged) {
          nextEventsByScope = { ...state.eventsByScope };
          bucket = { ...(bucket ?? {}) };
          nextEventsByScope[scopeKey] = bucket;
          bucketChanged = true;
        }
        delete bucket[entry.tempEventId];
      }
    }

    if (!bucketChanged) {
      return { messages: nextMessages };
    }

    return {
      messages: nextMessages,
      eventsByScope: nextEventsByScope,
    };
  });
}
