import { randomBytes } from "crypto";
import type { EndpointTrafficCaptureMode } from "@prisma/client";

const BASE32_ALPHABET = "abcdefghijklmnopqrstuvwxyz234567";

export function endpointPreviewBaseHost(): string {
  return process.env.TRACE_ENDPOINT_PREVIEW_BASE_HOST?.trim() || "preview.localhost";
}

export function endpointPreviewScheme(): string {
  return process.env.TRACE_ENDPOINT_PREVIEW_PUBLIC_SCHEME?.trim() || "http";
}

export function endpointProxyRequestTimeoutMs(): number {
  const parsed = Number(process.env.TRACE_ENDPOINT_PROXY_REQUEST_TIMEOUT_MS);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : 60_000;
}

export function endpointTrafficRetentionHours(): number {
  const parsed = Number(process.env.TRACE_ENDPOINT_TRAFFIC_RETENTION_HOURS);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : 24;
}

export function endpointTrafficMaxBodyBytes(): number {
  const parsed = Number(process.env.TRACE_ENDPOINT_TRAFFIC_MAX_BODY_BYTES);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : 65_536;
}

export function endpointProxyMaxRequestBodyBytes(): number {
  const parsed = Number(process.env.TRACE_ENDPOINT_PROXY_MAX_REQUEST_BODY_BYTES);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : 25 * 1024 * 1024;
}

export function buildEndpointUrl(key: string): string {
  return `${endpointPreviewScheme()}://${key}.${endpointPreviewBaseHost()}`;
}

export function generateEndpointKey(length = 12): string {
  const bytes = randomBytes(length);
  let key = "";
  for (const byte of bytes) {
    key += BASE32_ALPHABET[byte % BASE32_ALPHABET.length];
  }
  return key;
}

export function extractEndpointKey(hostHeader: string | undefined | null): string | null {
  if (!hostHeader) return null;
  const host = hostHeader.split(":")[0]?.toLowerCase();
  const baseHost = endpointPreviewBaseHost().toLowerCase().split(":")[0];
  if (!host || host === baseHost || !host.endsWith(`.${baseHost}`)) return null;
  const key = host.slice(0, -1 * (`.${baseHost}`).length).split(".").at(-1);
  return key && /^[a-z0-9-]+$/.test(key) ? key : null;
}

export function sanitizeHeaders(
  headers: Record<string, string | string[] | undefined>,
): Record<string, string | string[]> {
  const sanitized: Record<string, string | string[]> = {};
  for (const [rawName, value] of Object.entries(headers)) {
    if (value == null) continue;
    const name = rawName.toLowerCase();
    if (
      name === "authorization" ||
      name === "cookie" ||
      name === "set-cookie" ||
      name === "x-api-key" ||
      name === "x-auth-token" ||
      name.includes("token") ||
      name.includes("secret") ||
      name.includes("key")
    ) {
      sanitized[rawName] = "[redacted]";
      continue;
    }
    sanitized[rawName] = value;
  }
  return sanitized;
}

const TRACE_SESSION_COOKIE = "trace_token";

// Hop-by-hop headers (RFC 7230 §6.1) must not be relayed across a proxy hop.
const HOP_BY_HOP_HEADERS = new Set([
  "connection",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailer",
  "transfer-encoding",
  "upgrade",
]);

// WebSocket handshake headers are regenerated by the runtime's outbound client.
const WS_HANDSHAKE_HEADERS = new Set([
  "host",
  "sec-websocket-key",
  "sec-websocket-version",
  "sec-websocket-extensions",
  "sec-websocket-accept",
  "sec-websocket-protocol",
]);

// Trace credentials live in the session cookie plus __trace_-prefixed cookies
// (e.g. the endpoint preview cookie). Strip those pairs so the proxied
// application keeps its own cookies but never receives Trace credentials.
function stripTraceSessionCookie(value: string): string | null {
  const kept = value
    .split(";")
    .map((part) => part.trim())
    .filter((part) => {
      if (!part) return false;
      const name = part.split("=")[0]?.trim().toLowerCase() ?? "";
      return name !== TRACE_SESSION_COOKIE && !name.startsWith("__trace_");
    });
  return kept.length ? kept.join("; ") : null;
}

// Build the header set forwarded to the runtime-hosted application. Trace
// credentials and hop-by-hop headers are removed so untrusted app code can never
// observe the caller's Trace session.
export function forwardableRequestHeaders(
  headers: Record<string, string | string[] | undefined>,
  options?: { websocket?: boolean },
): Record<string, string | string[]> {
  const forwarded: Record<string, string | string[]> = {};
  for (const [rawName, value] of Object.entries(headers)) {
    if (value == null) continue;
    const name = rawName.toLowerCase();
    if (name === "authorization" || name === "proxy-authorization") continue;
    if (HOP_BY_HOP_HEADERS.has(name)) continue;
    if (options?.websocket && WS_HANDSHAKE_HEADERS.has(name)) continue;
    if (name === "cookie") {
      const cookie = Array.isArray(value) ? value.join("; ") : value;
      const stripped = stripTraceSessionCookie(cookie);
      if (stripped) forwarded[rawName] = stripped;
      continue;
    }
    forwarded[rawName] = value;
  }
  return forwarded;
}

export function webSocketProtocols(
  headers: Record<string, string | string[] | undefined>,
): string[] {
  const value = headers["sec-websocket-protocol"];
  const values = Array.isArray(value) ? value : value ? [value] : [];
  return [
    ...new Set(
      values
        .flatMap((entry) => entry.split(","))
        .map((protocol) => protocol.trim())
        .filter(Boolean),
    ),
  ];
}

// Strip hop-by-hop headers from the application's response before relaying it
// back to the caller; the proxy manages framing itself.
export function forwardableResponseHeaders(
  headers: Record<string, string | string[]>,
): Record<string, string | string[]> {
  const forwarded: Record<string, string | string[]> = {};
  for (const [rawName, value] of Object.entries(headers)) {
    if (HOP_BY_HOP_HEADERS.has(rawName.toLowerCase())) continue;
    forwarded[rawName] = value;
  }
  return forwarded;
}

export function shouldCaptureHeaders(mode: EndpointTrafficCaptureMode): boolean {
  return mode === "headers" || mode === "full";
}

export function shouldCaptureBodies(mode: EndpointTrafficCaptureMode): boolean {
  return mode === "full";
}

export function bodyPreview(buffer: Buffer, maxBytes = endpointTrafficMaxBodyBytes()) {
  const truncated = buffer.byteLength > maxBytes;
  const preview = buffer.subarray(0, maxBytes);
  return {
    preview: preview.toString("utf8"),
    bytes: buffer.byteLength,
    truncated,
  };
}
